# -*- coding: utf-8 -*-
"""Slink Lingo w Bard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10erM8_r9A6Va6iykY-F_xeEnZjrI-lQi
"""

def flip_even_line_words(text):
    lines = text.split("\n")
    modified_lines = []
    for index, line in enumerate(lines):
        if index % 2 != 0:
            words = line.split()
            modified_words = []
            for word in words:
                modified_words.append(word[::-1])
            modified_lines.append(" ".join(modified_words[::-1]))
        else:
            modified_lines.append(line)

    return "\n".join(modified_lines)

if __name__ == "__main__":
    with open("input_text.txt", "r") as input_file:
        text = input_file.read()

    modified_text = flip_even_line_words(text)

    with open("output_text.txt", "w") as output_file:
        output_file.write(modified_text)